# services:
#   express:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     container_name: ass-express
#     ports:
#       - "3000:3000"
#     volumes:
#       - ./src:/app/src
#       - ./index.js:/app/index.js
#       - .env:/app/.env
#   mongodb:
#     build:
#       context: .
#       dockerfile: Dockerfile-mongo
#     container_name: ass-mongodb
#     ports:
#       - "27019:27017"
#     volumes:
#       - mongodbdata:/data/db
#   redis:
#     image: redis:5
#     container_name: ass-redis
#     ports:
#       - 6379:6379
#   redis-commander:
#     image: rediscommander/redis-commander:latest
#     environment:
#       - REDIS_HOSTS=local:ass-redis:6379
#     ports:
#       - "8082:8081"
#     depends_on:
#       - redis
# volumes:
#   mongodbdata:

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile-nginx
    container_name: load-balancer
    depends_on:
      - express
    environment:
      - NGINX_SERVER_NAME=localhost
      - EXPRESS_HOST_1=${EXPRESS_CONTAINER}-1
      # - EXPRESS_HOST_2=${EXPRESS_CONTAINER}-2
      # - EXPRESS_HOST_1=express-assignment-express-1
      # - EXPRESS_HOST_2=express-assignment-express-2
      # - EXPRESS_HOST_3=express-assignment-express-3
      - EXPRESS_PORT=3000
      - NGINX_MAX_BODY=100M
    ports:
      - 3000:3000
  express:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/app/src
      - ./index.js:/app/index.js
      - .env:/app/.env
    scale: 1
    depends_on:
      - mongodb
      - redis
  mongodb:
    build:
      context: .
      dockerfile: Dockerfile-mongo
    container_name: ass-mongodb
    ports:
      - "27019:27017"
    volumes:
      - mongodbdata:/data/db
  redis:
    image: redis:5
    container_name: ass-redis
    ports:
      - 6379:6379
  redis-commander:
    image: rediscommander/redis-commander:latest
    environment:
      - REDIS_HOSTS=local:ass-redis:6379
    ports:
      - "8082:8081"
    depends_on:
      - redis
volumes:
  mongodbdata:



